import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { userService } from '../services/userService'
import { chatService } from '../services/chatService'
import '../styles/public-profile.css'

const initials = (name) => name?.split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase() || '?'

export default function PublicProfile() {
  const { userId } = useParams(); const { user: currentUser, updateUser } = useAuth()
  const navigate = useNavigate()
  const [profile, setProfile] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [following, setFollowing] = useState(false); const [busy, setBusy] = useState(false); const [requestStatus, setRequestStatus] = useState('')
  useEffect(() => { let active = true; async function load() { try { setLoading(true); const data = await userService.getPublicProfile(userId); if (!active) return; setProfile(data); if (currentUser && currentUser.id !== userId) { const status = await userService.getFollowStatus(userId); if (active) setFollowing(status.following) } } catch (err) { if (active) setError(err.message || 'Unable to load profile.') } finally { if (active) setLoading(false) } } load(); return () => { active = false } }, [userId, currentUser?.id])
  async function toggleFollow() { try { setBusy(true); const result = await userService.toggleFollow(userId); setFollowing(result.following); setProfile(current => ({ ...current, user: { ...current.user, followersCount: result.targetFollowersCount } })); updateUser({ ...currentUser, followingCount: result.currentFollowingCount }) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  async function sendMessageRequest() { try { setBusy(true); setError(''); const result = await chatService.createMessageRequest(userId); setRequestStatus(result.message) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  if (loading) return <main className="public-profile-page"><div className="profile-message">Loading profile…</div></main>
  if (error || !profile?.user) return <main className="public-profile-page"><div className="profile-message error">{error || 'Profile not found.'}</div></main>
  const { user, articles = [] } = profile; const ownProfile = currentUser?.id === user.id
  return <main className="public-profile-page"><section className="public-profile-container"><Link className="profile-back-link" to={currentUser ? `/${currentUser.role}/home` : '/login'}>← Back</Link><header className="public-profile-header"><div className="public-profile-photo">{user.profilePhoto ? <img src={user.profilePhoto} alt={user.name} /> : <span>{initials(user.name)}</span>}</div><div className="public-profile-info"><div className="public-profile-topline"><div><h1>@{user.username || user.name.toLowerCase().replace(/\s+/g, '.')}</h1><p className="public-profile-name">{user.name} <span>{user.role}</span></p></div>{currentUser && !ownProfile && <div className="public-profile-actions"><button className={`public-follow-button ${following ? 'following' : ''}`} type="button" onClick={toggleFollow} disabled={busy}>{busy ? 'Please wait…' : following ? 'Following' : 'Follow'}</button>{following ? <button className="public-message-button" type="button" onClick={() => navigate(`/chat?user=${user.id}`)}>Message</button> : <button className="public-message-button request" type="button" onClick={sendMessageRequest} disabled={busy || !!requestStatus}>{busy ? 'Please wait…' : requestStatus ? 'Request sent' : 'Send message request'}</button>}</div>}</div>{requestStatus && <p className="message-request-status">{requestStatus}</p>}<div className="profile-stats"><span><strong>{articles.length}</strong> articles</span><span><strong>{user.followersCount}</strong> followers</span><span><strong>{user.followingCount}</strong> following</span></div>{user.bio && <p className="profile-bio">{user.bio}</p>}</div></header><section className="published-articles-section"><div className="public-section-heading"><span className="eyebrow">Published work</span><h2>Stories by {user.name}</h2></div>{articles.length === 0 ? <div className="no-articles">No published articles yet.</div> : <div className="public-article-grid">{articles.map(article => <Link key={article.id} to={currentUser ? `/${currentUser.role}/article/${article.id}` : '/login'} className="public-article-card"><div className="article-thumbnail">{article.coverImage ? <img src={article.coverImage} alt="" /> : <span>{article.category}</span>}<div className="public-article-overlay"><span>♡ {article.likesCount || 0}</span><span>◉ {article.views || 0}</span></div></div><h3>{article.title}</h3><p>{article.category} · {article.readMinutes} min read</p></Link>)}</div>}</section></section></main>
}
